### ISSUE TITLE
login with invalid data

### ISSUE THREAD

**Issue by matavak** [CHADBUCK13/soen341#88]
**Description:**
If the user attempts to use an an invalid email or the wrong password to login, the website crashes.

**Related Epic/Story:**
#45 #25 
![bug1](https://user-images.githubusercontent.com/94761378/160167559-7e8e9b49-990f-4be1-a72e-7142f703f1d1.PNG)
![bug2](https://user-images.githubusercontent.com/94761378/160167574-6ad8266c-7dc4-417c-b1c3-08c4c44271a6.PNG)

**Comment by CHADBUCK13** [comment]
Looks like incorrect handling of return value from backend login function. Should be an easy fix
